/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package infz.d.project.gui;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Method
 */
public class Spelbord extends javax.swing.JPanel {
    int breedte = 50, hoogte = 50, cellGrootte = 0;
    int xPos, yPos, rows, columns;
    ArrayList<String> vakjesInhoud = new ArrayList<String>();
    Vakje[][] vakjeBuur = new Vakje[5][5];
    
    /**
     * Creates new form Spelbord
     */
    public Spelbord() {
        initComponents();
        genereerSpelbordPanelGegevens();
    }
    
    // Panel gegevens
    private void genereerSpelbordPanelGegevens() {
        this.setSize(400, 600);
        this.setBackground(Color.BLACK);
        getSpelbordTxtFile();
        genereerVakjes();
    }
    
    public void start() {
        genereerSpelbordPanelGegevens();
    }
    // Get posities van entiteiten die een spel vormen uit de txt file.
    private void getSpelbordTxtFile() {
        try {
            Scanner read = new Scanner(new File("txt/maze.txt"));
            int lineCount = 0;
            while (read.hasNextLine()) {
                String line = read.nextLine();
                vakjesInhoud.add(line);
                System.out.println(line);
                if (line.contains("5")) {
                    yPos = lineCount;
                    xPos = line.indexOf('5');
                }
                lineCount++;
            }
            read.close();

            rows = vakjesInhoud.size();
            columns = vakjesInhoud.get(0).length();

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        
        for(int row = 0; row<rows; row++){
                for(int column = 0; column<columns; column++){
                    switch(charAt(row, column)){
                        case 0:
                            break;
                        case 1:
                            // muur
                            break;
                        case 2:
                            // Bolletje
                            break;
                        case 3:
                            // Superbolletje
                            break;
                        case 4:
                            // Spookje
                            break;
                        case 5:
                            // Pacman
                            break;
                        default:
                            break;
                    }
                }
            }
    }
    // 
    private void genereerVakjes() {
        Vakje vakje;
        int muurAantal = 0;
        
        for(int row = 0; row < rows; row++){
            for (int column = 0; column < columns; column++){
                int output = charAt(row, column);
                System.out.println("Output: " + output);
                if(output==1)
                    muurAantal++;
            }
        }
        System.out.println("Totaal muur: " + muurAantal);
        /*
        for(int i = 0; i < 25; i++){
            vakje = new Vakje(rows, columns, (output == 1 ? true : false));
            System.out.println("Aantal row:" + rows + ""
                    + "\nAantal Column: " + columns + "Totaal muur: " + muurAantal);
        }*/
    }
    
    private char charAt(int row, int column) {
            return vakjesInhoud.get(row).charAt(column);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
